### PR TITLE
Adding Submission Error entity and endpoints

### PR DESCRIPTION
**Pull request by aaclan-ebi**

### CODE REVIEW

**Comment by tburdett** [comment]
I'll provide some details in line, but in general you've done a nice job here @aaclan-ebi, thanks.

I'd suggest tweaking your `SubmissionErrors` object a little bit. There's actually a new IETF RFC covering this ('Problem Details for HTTP APIs'), see https://tools.ietf.org/html/rfc7807.

There's also a library that implements this RFC we could use, https://github.com/zalando/problem.  And possibly the spring integration library https://github.com/zalando/problem-spring-web, although I had a quick read of the docs for this and couldn't figure out how problem details are actually communicated.

I also don't think you need the `SubmissionErrorsRepository`.  We won't want to provide global access to `SubmissionErrors`, they should be scoped to a particular `SubmissionEnvelope` which makes them a [value object](https://en.wikipedia.org/wiki/Value_object). It's fine to just drop this repo and have the errors embedded from submission envelopes.

There's also two general requirements as far as I can see - 1) is to store the errors on a submission envelope so you can see all the errors that have happened for a submission envelope, and 2) is to communicate the details of that error when it occurs via the correct HTTP error code (and wrapping the details). I think you have 1) done with this PR but it looks like 2) is currently not handled and needs a little bit of thinking about.

In terms of priorities, you don't need to do all this now, we can evolve over several iterations.  The minimum though is to not add a new repository and a new set of API endpoints and instead embed the problem details on the `SubmissionEnvelope`, this gives us more freedom to modify the format of this object going forward.

**Comment by aaclan-ebi** [comment]
@tburdett , the reason I didn't embed it to the submission envelope is that I want to avoid locking error with submission state updates. Thoughts?

**Comment by tburdett** [comment]
OK, that's a reasonable concern. My initial reaction is that this will be much less of a problem here because errors should be infrequent, whereas state transitions (which caused many problems) were frequent and horrible! I think the cost of an extra repository and of the reverse lookups on that repository probably outweighs the gains from the locking on submission state updates. If we do find locks occur more frequently with embedded errors we might have to more carefully revisit the mechanisms for submission envelope updates... which I am pretty sure we need to do already!

**Comment by rolando-ebi** [comment]
Either or is good with me. 

I'd just keep the .save() methods in the SubmissionEnvelopeService so we can handle optimistic locks there instead of in the controller.

**Comment by aaclan-ebi** [comment]
Implemented the embedded submission error, merged the branch now to master for testing in dev

**Pull request merged**
